### ISSUE TITLE
I use xray module. Is there a way to auto update geosite and geoip sir?

### ISSUE THREAD

**Issue by Thaomtam** [CHIZI-0618/box4magisk#5]

**Comment by CHIZI-0618** [comment]
Regularly execute scripts automatically using [`crontab`](https://man7.org/linux/man-pages/man8/cron.8.html)
  
In order to get the latest geosite.dat the following command can be used
`su -c '/data/adb/magisk/busybox wget https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat -O /data/adb/box/xray/geosite.dat'`

**Comment by Thaomtam** [comment]
> 

This box is great. Lightweight, suitable for all models. Really thank you.

**Comment by CHIZI-0618** [comment]
It is a great honor that this project can help you

**Comment by Thaomtam** [comment]
taaming fork your project. But not as good as you. You are my idol. I am so lucky to know this project of yours
