### ISSUE TITLE
Hi, is there any script to update core itself sir. For example I need to update xray core automatically. Tks

### ISSUE THREAD

**Issue by Thaomtam** [CHIZI-0618/box4magisk#6]

**Comment by CHIZI-0618** [comment]
Regularly execute scripts automatically using crontab

In order to get the latest xray core the following command can be used
`su -c '/data/adb/magisk/busybox wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-android-arm64-v8a.zip && /data/adb/magisk/busybox unzip Xray-android-arm64-v8a.zip xray -d /data/adb/box/bin/'`

**Comment by Thaomtam** [comment]
thank you sir

**Comment by Thaomtam** [comment]
thank you sir

**Comment by Thaomtam** [comment]
I tried. And get the following error message. 
$ su -c '/data/adb/magisk/busybox wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-android-arm64-v8a.zip && /data/adb/magisk/busybox unzip Xray-android-arm64-v8a.zip xray -d /data/adb/box/bin/'
Connecting to github.com (20.205.243.166:443)
wget: note: TLS certificate validation not implemented
Connecting to github.com (20.205.243.166:443)
Connecting to objects.githubusercontent.com (185.199.108.133:443)
wget: can't open 'Xray-android-arm64-v8a.zip': File exists
~ $

**Comment by CHIZI-0618** [comment]
> 

The file was not downloaded successfully
